AddCredentialConfigForMsoMdoc:
  InjiCertify_AddCredentialConfig_mdoc_all_Valid_Smoke_sid:
    endPoint: $INJICERTIFYBASEURL$/v1/certify/credential-configurations
    uniqueIdentifier: TC_InjiCertify_addCredentialtypeformdoc_01
    description: Add credential configuration for mdoc
    role: noauth
    restMethod: post
    inputTemplate: injicertify/mDocMDL/AddCredentialConfigurationForMdoc/AddCredentialConfigurationForMdoc
    outputTemplate: injicertify/mDocMDL/AddCredentialConfigurationForMdoc/AddCredentialConfigurationResultForMdoc
    input: '{
      "nameSpaces": [
        {
          "namespace": "org.iso.18013.5.1",
          "elements": [
            {
              "digestID": 0,
              "elementIdentifier": "family_name",
              "elementValue": "${familyName}",
              "isString": true
            },
            {
              "digestID": 1,
              "elementIdentifier": "given_name",
              "elementValue": "${givenName}",
              "isString": true
            },
            {
              "digestID": 2,
              "elementIdentifier": "birth_date",
              "elementValue": "${birthDate}",
              "isString": true
            },
            {
              "digestID": 7,
              "elementIdentifier": "driving_privileges",
              "elementValue": "${drivingPrivileges}",
              "isString": false
            }
          ]
        }
      ],
      "contextURLs": [],
      "credentialTypes": [],
      "didUrl": "did:web:inji.github.io:inji-config:collab:mock-mdl",
      "keyManagerAppId": "CERTIFY_VC_SIGN_EC_R1",
      "keyManagerRefId": "EC_SECP256R1_SIGN",
      "signatureAlgo": "ES256",
      "signatureCryptoSuite": "EcdsaSecp256r1Signature2019",
      "doctype": "org.iso.18013.5.1.mDL_new",
      "credentialFormat": "mso_mdoc",
      "display_name": "Mobile Driving License",
      "displayOrder": [
        {"displayOrder_values": "org.iso.18013.5.1.mDL~family_name"},
        {"displayOrder_values": "org.iso.18013.5.1.mDL~given_name"},
        {"displayOrder_values": "org.iso.18013.5.1.mDL~birth_date"},
        {"displayOrder_values": "org.iso.18013.5.1.mDL~document_number"},
        {"displayOrder_values": "org.iso.18013.5.1.mDL~portrait"},
        {"displayOrder_values": "org.iso.18013.5.1.mDL~driving_privileges"}
      ],
      "scope": "sample_vc_mdoc",
      "credentialConfigKeyId": "DrivingLicenseCredential_automation",
      "msoMdocClaims": [
        {
          "namespace": "org.iso.18013.5.1.mDL",
          "claims": [
            {
              "claim_name": "driving_privileges",
              "display": [
                {"display_name": "Driving Privileges", "display_locale": "en"}
              ]
            },
            {
              "claim_name": "document_number",
              "display": [
                {"display_name": "Document Number", "display_locale": "en"}
              ]
            }
          ]
        }
      ]
    }'
    output: '{
      "status": "active"
    }'

  InjiCertify_AddCredentialConfig_mdoc_withoutDocType:
    endPoint: $INJICERTIFYBASEURL$/v1/certify/credential-configurations
    uniqueIdentifier: TC_InjiCertify_addCredentialtypeformdoc_02
    description: Add credential configuration for mdoc without doctype
    role: noauth
    restMethod: post
    inputTemplate: injicertify/mDocMDL/AddCredentialConfigurationForMdoc/AddCredentialConfigurationWithoutDocTypeForMdoc
    outputTemplate: injicertify/error
    input: '{
      "nameSpaces": [
        {
          "namespace": "org.iso.18013.5.1",
          "elements": [
            {
              "digestID": 0,
              "elementIdentifier": "family_name",
              "elementValue": "${familyName}",
              "isString": true
            },
            {
              "digestID": 1,
              "elementIdentifier": "given_name",
              "elementValue": "${givenName}",
              "isString": true
            },
            {
              "digestID": 2,
              "elementIdentifier": "birth_date",
              "elementValue": "${birthDate}",
              "isString": true
            },
            {
              "digestID": 7,
              "elementIdentifier": "driving_privileges",
              "elementValue": "${drivingPrivileges}",
              "isString": false
            }
          ]
        }
      ],
      "contextURLs": [],
      "credentialTypes": [],
      "didUrl": "did:web:inji.github.io:inji-config:collab:mock-mdl",
      "keyManagerAppId": "CERTIFY_VC_SIGN_EC_R1",
      "keyManagerRefId": "EC_SECP256R1_SIGN",
      "signatureAlgo": "ES256",
      "signatureCryptoSuite": "EcdsaSecp256r1Signature2019",
      "credentialFormat": "mso_mdoc",
      "display_name": "Mobile Driving License",
      "displayOrder": [
        {"displayOrder_values": "org.iso.18013.5.1.mDL~family_name"},
        {"displayOrder_values": "org.iso.18013.5.1.mDL~given_name"},
        {"displayOrder_values": "org.iso.18013.5.1.mDL~birth_date"},
        {"displayOrder_values": "org.iso.18013.5.1.mDL~document_number"},
        {"displayOrder_values": "org.iso.18013.5.1.mDL~portrait"},
        {"displayOrder_values": "org.iso.18013.5.1.mDL~driving_privileges"}
      ],
      "scope": "sample_vc_mdoc",
      "credentialConfigKeyId": "DrivingLicenseCredential_automation",
      "msoMdocClaims": [
        {
          "namespace": "org.iso.18013.5.1.mDL",
          "claims": [
            {
              "claim_name": "driving_privileges",
              "display": [
                {"display_name": "Driving Privileges", "display_locale": "en"}
              ]
            },
            {
              "claim_name": "document_number",
              "display": [
                {"display_name": "Document Number", "display_locale": "en"}
              ]
            }
          ]
        }
      ]
    }'
    output: '{
      "errors": [
        {
          "errorCode": "mso_mdoc_mandatory_fields_missing"
        }
      ]
    }'

  InjiCertify_AddCredentialConfig_mdoc_withoutClaims:
    endPoint: $INJICERTIFYBASEURL$/v1/certify/credential-configurations
    uniqueIdentifier: TC_InjiCertify_addCredentialtypeformdoc_03
    description: Add credential configuration for mdoc without msoMdocClaims
    role: noauth
    restMethod: post
    inputTemplate: injicertify/mDocMDL/AddCredentialConfigurationForMdoc/AddCredentialConfigurationWithoutClaims
    outputTemplate: injicertify/error
    input: '{
      "nameSpaces": [
        {
          "namespace": "org.iso.18013.5.1",
          "elements": [
            {
              "digestID": 0,
              "elementIdentifier": "family_name",
              "elementValue": "${familyName}",
              "isString": true
            },
            {
              "digestID": 1,
              "elementIdentifier": "given_name",
              "elementValue": "${givenName}",
              "isString": true
            },
            {
              "digestID": 2,
              "elementIdentifier": "birth_date",
              "elementValue": "${birthDate}",
              "isString": true
            },
            {
              "digestID": 7,
              "elementIdentifier": "driving_privileges",
              "elementValue": "${drivingPrivileges}",
              "isString": false
            }
          ]
        }
      ],
      "contextURLs": [],
      "credentialTypes": [],
      "didUrl": "did:web:inji.github.io:inji-config:collab:mock-mdl",
      "keyManagerAppId": "CERTIFY_VC_SIGN_EC_R1",
      "keyManagerRefId": "EC_SECP256R1_SIGN",
      "signatureAlgo": "ES256",
      "signatureCryptoSuite": "EcdsaSecp256r1Signature2019",
      "doctype": "org.iso.18013.5.1.mDL",
      "credentialFormat": "mso_mdoc",
      "display_name": "Mobile Driving License",
      "displayOrder": [
        {"displayOrder_values": "org.iso.18013.5.1.mDL~family_name"},
        {"displayOrder_values": "org.iso.18013.5.1.mDL~given_name"},
        {"displayOrder_values": "org.iso.18013.5.1.mDL~birth_date"},
        {"displayOrder_values": "org.iso.18013.5.1.mDL~document_number"},
        {"displayOrder_values": "org.iso.18013.5.1.mDL~portrait"},
        {"displayOrder_values": "org.iso.18013.5.1.mDL~driving_privileges"}
      ],
      "scope": "sample_vc_mdoc",
      "credentialConfigKeyId": "DrivingLicenseCredential_automation"
    }'
    output: '{
      "errors": [
        {
          "errorCode": "invalid_request"
        }
      ]
    }'

  InjiCertify_AddCredentialConfig_mdoc_DuplicateDocType:
    endPoint: $INJICERTIFYBASEURL$/v1/certify/credential-configurations
    uniqueIdentifier: TC_InjiCertify_addCredentialtypeformdoc_04
    description: Add credential configuration for mdoc with duplicate doctype
    role: noauth
    restMethod: post
    inputTemplate: injicertify/mDocMDL/AddCredentialConfigurationForMdoc/AddCredentialConfigurationForMdoc
    outputTemplate: injicertify/error
    input: '{
      "nameSpaces": [
        {
          "namespace": "org.iso.18013.5.1",
          "elements": [
            {
              "digestID": 0,
              "elementIdentifier": "family_name",
              "elementValue": "${familyName}",
              "isString": true
            },
            {
              "digestID": 1,
              "elementIdentifier": "given_name",
              "elementValue": "${givenName}",
              "isString": true
            },
            {
              "digestID": 2,
              "elementIdentifier": "birth_date",
              "elementValue": "${birthDate}",
              "isString": true
            },
            {
              "digestID": 7,
              "elementIdentifier": "driving_privileges",
              "elementValue": "${drivingPrivileges}",
              "isString": false
            }
          ]
        }
      ],
      "contextURLs": [],
      "credentialTypes": [],
      "didUrl": "did:web:inji.github.io:inji-config:collab:mock-mdl",
      "keyManagerAppId": "CERTIFY_VC_SIGN_EC_R1",
      "keyManagerRefId": "EC_SECP256R1_SIGN",
      "signatureAlgo": "ES256",
      "signatureCryptoSuite": "EcdsaSecp256r1Signature2019",
      "doctype": "org.iso.18013.5.1.mDL",
      "credentialFormat": "mso_mdoc",
      "display_name": "Mobile Driving License",
      "displayOrder": [
        {"displayOrder_values": "org.iso.18013.5.1.mDL~family_name"},
        {"displayOrder_values": "org.iso.18013.5.1.mDL~given_name"},
        {"displayOrder_values": "org.iso.18013.5.1.mDL~birth_date"},
        {"displayOrder_values": "org.iso.18013.5.1.mDL~document_number"},
        {"displayOrder_values": "org.iso.18013.5.1.mDL~portrait"},
        {"displayOrder_values": "org.iso.18013.5.1.mDL~driving_privileges"}
      ],
      "scope": "sample_vc_mdoc",
      "credentialConfigKeyId": "DrivingLicenseCredential_automation",
      "msoMdocClaims": [
        {
          "namespace": "org.iso.18013.5.1.mDL",
          "claims": [
            {
              "claim_name": "driving_privileges",
              "display": [
                {"display_name": "Driving Privileges", "display_locale": "en"}
              ]
            },
            {
              "claim_name": "document_number",
              "display": [
                {"display_name": "Document Number", "display_locale": "en"}
              ]
            }
          ]
        }
      ]
    }'
    output: '{
      "errors": [
        {
          "errorCode": "mso_mdoc_config_exists"
        }
      ]
    }'
